# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cluster.proto import cluster_pb2 as cluster_dot_proto_dot_cluster__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cluster/proto/cluster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MasterServiceStub(object):
    """Master Service - exposed by master node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/cluster.MasterService/RegisterWorker',
                request_serializer=cluster_dot_proto_dot_cluster__pb2.WorkerRegistration.SerializeToString,
                response_deserializer=cluster_dot_proto_dot_cluster__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/cluster.MasterService/Heartbeat',
                request_serializer=cluster_dot_proto_dot_cluster__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=cluster_dot_proto_dot_cluster__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ReportTaskResult = channel.unary_unary(
                '/cluster.MasterService/ReportTaskResult',
                request_serializer=cluster_dot_proto_dot_cluster__pb2.TaskResult.SerializeToString,
                response_deserializer=cluster_dot_proto_dot_cluster__pb2.Ack.FromString,
                _registered_method=True)


class MasterServiceServicer(object):
    """Master Service - exposed by master node
    """

    def RegisterWorker(self, request, context):
        """Worker registers with master on startup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Worker sends periodic heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTaskResult(self, request, context):
        """Worker reports task completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=cluster_dot_proto_dot_cluster__pb2.WorkerRegistration.FromString,
                    response_serializer=cluster_dot_proto_dot_cluster__pb2.RegistrationResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=cluster_dot_proto_dot_cluster__pb2.HeartbeatRequest.FromString,
                    response_serializer=cluster_dot_proto_dot_cluster__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ReportTaskResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTaskResult,
                    request_deserializer=cluster_dot_proto_dot_cluster__pb2.TaskResult.FromString,
                    response_serializer=cluster_dot_proto_dot_cluster__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cluster.MasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cluster.MasterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MasterService(object):
    """Master Service - exposed by master node
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.MasterService/RegisterWorker',
            cluster_dot_proto_dot_cluster__pb2.WorkerRegistration.SerializeToString,
            cluster_dot_proto_dot_cluster__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.MasterService/Heartbeat',
            cluster_dot_proto_dot_cluster__pb2.HeartbeatRequest.SerializeToString,
            cluster_dot_proto_dot_cluster__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.MasterService/ReportTaskResult',
            cluster_dot_proto_dot_cluster__pb2.TaskResult.SerializeToString,
            cluster_dot_proto_dot_cluster__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub(object):
    """Worker Service - exposed by worker nodes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssignTask = channel.unary_unary(
                '/cluster.WorkerService/AssignTask',
                request_serializer=cluster_dot_proto_dot_cluster__pb2.TaskAssignment.SerializeToString,
                response_deserializer=cluster_dot_proto_dot_cluster__pb2.TaskAck.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/cluster.WorkerService/GetStatus',
                request_serializer=cluster_dot_proto_dot_cluster__pb2.StatusRequest.SerializeToString,
                response_deserializer=cluster_dot_proto_dot_cluster__pb2.WorkerStatus.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/cluster.WorkerService/CancelTask',
                request_serializer=cluster_dot_proto_dot_cluster__pb2.TaskCancellation.SerializeToString,
                response_deserializer=cluster_dot_proto_dot_cluster__pb2.Ack.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """Worker Service - exposed by worker nodes
    """

    def AssignTask(self, request, context):
        """Master assigns task to worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Master requests worker status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Master cancels a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssignTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignTask,
                    request_deserializer=cluster_dot_proto_dot_cluster__pb2.TaskAssignment.FromString,
                    response_serializer=cluster_dot_proto_dot_cluster__pb2.TaskAck.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=cluster_dot_proto_dot_cluster__pb2.StatusRequest.FromString,
                    response_serializer=cluster_dot_proto_dot_cluster__pb2.WorkerStatus.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=cluster_dot_proto_dot_cluster__pb2.TaskCancellation.FromString,
                    response_serializer=cluster_dot_proto_dot_cluster__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cluster.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cluster.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Worker Service - exposed by worker nodes
    """

    @staticmethod
    def AssignTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.WorkerService/AssignTask',
            cluster_dot_proto_dot_cluster__pb2.TaskAssignment.SerializeToString,
            cluster_dot_proto_dot_cluster__pb2.TaskAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.WorkerService/GetStatus',
            cluster_dot_proto_dot_cluster__pb2.StatusRequest.SerializeToString,
            cluster_dot_proto_dot_cluster__pb2.WorkerStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.WorkerService/CancelTask',
            cluster_dot_proto_dot_cluster__pb2.TaskCancellation.SerializeToString,
            cluster_dot_proto_dot_cluster__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
